"""Lexical, semantic, and Reciprocal Rank Fusion retrieval."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Iterable

from transcription.db import connect_from_environment
from transcription.embeddings import LocalEmbedder


logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SearchResult:
    """One retrieved transcript chunk and its mode-specific score."""

    chunk_id: str
    source_file: str
    speaker_id: str
    start_time: float
    end_time: float
    text: str
    score: float


def _rows_to_results(rows: Iterable[tuple[Any, ...]]) -> list[SearchResult]:
    """Convert PostgreSQL result rows into stable application results."""
    results = [
        SearchResult(
            chunk_id=row[0],
            source_file=row[1],
            speaker_id=row[2],
            start_time=float(row[3]),
            end_time=float(row[4]),
            text=row[5],
            score=float(row[6]),
        )
        for row in rows
    ]
    logger.debug("Converted %d database rows into search results", len(results))
    return results


def lexical_search(connection, query: str, candidate_count: int) -> list[SearchResult]:
    """Retrieve candidates with PostgreSQL full-text search.

    ``websearch_to_tsquery`` provides user-friendly query syntax and the
    existing generated tsvector GIN index is used by the match predicate.
    ``ts_rank_cd`` ranks the lexical candidates; its score is not combined
    directly with vector scores.
    """
    sql = """
        SELECT chunk_id, source_file, speaker_id, start_time, end_time, text,
               ts_rank_cd(search_vector, websearch_to_tsquery('simple', %s)) AS score
        FROM transcript_chunks
        WHERE search_vector @@ websearch_to_tsquery('simple', %s)
        ORDER BY score DESC, chunk_id ASC
        LIMIT %s
    """
    logger.info("Running lexical retrieval: candidates=%d", candidate_count)
    logger.debug("Lexical query text: %r", query)
    rows = connection.execute(sql, (query, query, candidate_count)).fetchall()
    results = _rows_to_results(rows)
    logger.info("Lexical retrieval returned %d candidates", len(results))
    logger.debug("Lexical candidate IDs: %s", [result.chunk_id for result in results])
    return results


def semantic_search(
    connection,
    query_embedding: list[float],
    candidate_count: int,
) -> list[SearchResult]:
    """Retrieve candidates by exact pgvector cosine distance.

    The query embedding must be generated by the same local model used during
    ingestion. Document embeddings are read from PostgreSQL and are never
    regenerated during search.
    """
    vector_literal = "[" + ",".join(str(value) for value in query_embedding) + "]"
    sql = """
        SELECT chunk_id, source_file, speaker_id, start_time, end_time, text,
               1 - (embedding <=> %s::vector) AS score
        FROM transcript_chunks
        ORDER BY embedding <=> %s::vector ASC, chunk_id ASC
        LIMIT %s
    """
    logger.info(
        "Running semantic retrieval: candidates=%d embedding_dimension=%d",
        candidate_count,
        len(query_embedding),
    )
    rows = connection.execute(sql, (vector_literal, vector_literal, candidate_count)).fetchall()
    results = _rows_to_results(rows)
    logger.info("Semantic retrieval returned %d candidates", len(results))
    logger.debug("Semantic candidate IDs: %s", [result.chunk_id for result in results])
    return results


def rrf_fuse(
    ranked_lists: Iterable[Iterable[SearchResult]],
    *,
    rrf_k: int = 60,
    top_k: int | None = None,
) -> list[SearchResult]:
    """Fuse ranked result lists using Reciprocal Rank Fusion.

    For every list, rank 1 contributes ``1 / (rrf_k + 1)``. Results are
    deduplicated by ``chunk_id`` and retain the first available chunk fields.
    Ties are resolved by chunk ID for deterministic output.

    Args:
        ranked_lists: Independently ranked lexical or semantic result lists.
        rrf_k: RRF smoothing constant; default is 60.
        top_k: Optional maximum number of fused results.

    Returns:
        Results sorted by descending RRF score and deterministic chunk ID.

    Raises:
        ValueError: If ``rrf_k`` is negative or ``top_k`` is non-positive.
    """
    if rrf_k < 0:
        raise ValueError("rrf_k must be non-negative")
    if top_k is not None and top_k <= 0:
        raise ValueError("top_k must be positive")

    scores: dict[str, float] = {}
    representatives: dict[str, SearchResult] = {}
    list_count = 0
    total_candidates = 0
    for list_count, ranked in enumerate(ranked_lists, start=1):
        ranked = list(ranked)
        total_candidates += len(ranked)
        logger.debug("RRF list %d contains %d candidates", list_count, len(ranked))
        for rank, result in enumerate(ranked, start=1):
            scores[result.chunk_id] = scores.get(result.chunk_id, 0.0) + 1.0 / (rrf_k + rank)
            representatives.setdefault(result.chunk_id, result)
            logger.debug(
                "RRF contribution: list=%d rank=%d chunk_id=%s contribution=%.8f",
                list_count,
                rank,
                result.chunk_id,
                1.0 / (rrf_k + rank),
            )

    fused = [
        SearchResult(
            chunk_id=chunk_id,
            source_file=representatives[chunk_id].source_file,
            speaker_id=representatives[chunk_id].speaker_id,
            start_time=representatives[chunk_id].start_time,
            end_time=representatives[chunk_id].end_time,
            text=representatives[chunk_id].text,
            score=score,
        )
        for chunk_id, score in scores.items()
    ]
    fused.sort(key=lambda result: (-result.score, result.chunk_id))
    logger.info(
        "RRF fused %d candidate records into %d unique chunks using k=%d",
        total_candidates,
        len(fused),
        rrf_k,
    )
    logger.debug("RRF final IDs: %s", [result.chunk_id for result in fused[:top_k]])
    return fused[:top_k] if top_k is not None else fused


def search(
    query: str,
    mode: str = "hybrid",
    *,
    top_k: int = 5,
    candidate_count: int = 20,
    rrf_k: int = 60,
    connection=None,
    embedder: LocalEmbedder | None = None,
) -> list[SearchResult]:
    """Run lexical, semantic, or hybrid retrieval for one text query.

    Only the query is embedded in semantic and hybrid modes. The caller may
    provide an existing database connection and embedder for tests or reuse.
    """
    if mode not in {"lexical", "semantic", "hybrid"}:
        raise ValueError("mode must be lexical, semantic, or hybrid")
    if top_k <= 0 or candidate_count <= 0:
        raise ValueError("top_k and candidate_count must be positive")

    logger.info(
        "Starting search: mode=%s top_k=%d candidate_count=%d rrf_k=%d",
        mode,
        top_k,
        candidate_count,
        rrf_k,
    )
    logger.debug("Search query text: %r", query)
    owns_connection = connection is None
    if owns_connection:
        logger.info("Opening PostgreSQL connection from environment")
        connection = connect_from_environment()
    try:
        lexical = []
        semantic = []
        if mode in {"lexical", "hybrid"}:
            lexical = lexical_search(connection, query, candidate_count)
        if mode in {"semantic", "hybrid"}:
            embedder = embedder or LocalEmbedder()
            logger.info("Embedding query locally for %s retrieval", mode)
            query_embedding = embedder.encode([query])[0]
            semantic = semantic_search(connection, query_embedding, candidate_count)

        if mode == "lexical":
            final_results = lexical[:top_k]
        elif mode == "semantic":
            final_results = semantic[:top_k]
        else:
            final_results = rrf_fuse([lexical, semantic], rrf_k=rrf_k, top_k=top_k)
        logger.info("Search complete: returned %d results", len(final_results))
        logger.debug(
            "Final results: %s",
            [(result.chunk_id, round(result.score, 6)) for result in final_results],
        )
        return final_results
    finally:
        if owns_connection:
            logger.info("Closing PostgreSQL connection")
            connection.close()
