"""PostgreSQL storage and exact cosine-vector baseline queries."""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

from .embedding_config import DEFAULT_EMBEDDING_CONFIG


logger = logging.getLogger(__name__)


def connect_from_environment():
    """Open PostgreSQL using ``DATABASE_URL`` or standard ``PG*`` variables.

    Returns:
        An open psycopg connection.

    Raises:
        RuntimeError: If psycopg is not installed.
        KeyError: If no database name/user configuration is available.
    """
    try:
        import psycopg
    except ImportError as exc:
        raise RuntimeError("psycopg is required for PostgreSQL ingestion") from exc

    database_url = os.environ.get("DATABASE_URL")
    if database_url:
        return psycopg.connect(database_url)

    required = {"PGHOST": os.environ.get("PGHOST"), "PGDATABASE": os.environ.get("PGDATABASE"), "PGUSER": os.environ.get("PGUSER")}
    missing = [name for name, value in required.items() if not value]
    if missing:
        raise RuntimeError(
            "Set DATABASE_URL or PostgreSQL environment variables: " + ", ".join(missing)
        )
    kwargs: dict[str, Any] = {
        "host": required["PGHOST"],
        "dbname": required["PGDATABASE"],
        "user": required["PGUSER"],
    }
    for env_name, argument in [("PGPORT", "port"), ("PGPASSWORD", "password")]:
        if os.environ.get(env_name):
            kwargs[argument] = os.environ[env_name]
    return psycopg.connect(**kwargs)


def apply_schema(connection, schema_path: str | Path | None = None) -> None:
    """Create the pgvector table and GIN full-text index."""
    path = Path(schema_path or Path(__file__).parents[1] / "db" / "schema.sql")
    connection.execute(path.read_text(encoding="utf-8"))
    connection.commit()
    logger.info("Applied database schema: %s", path)


def insert_chunks(connection, chunks: list[dict[str, Any]], embeddings: list[list[float]]) -> int:
    """Insert chunks and precomputed embeddings using parameterized SQL.

    Existing ``chunk_id`` values are updated, making ingestion repeatable.
    Embeddings are generated by the caller and are never generated by SQL or
    by later search operations.
    """
    if len(chunks) != len(embeddings):
        raise ValueError("Chunk and embedding counts differ")
    sql = """
        INSERT INTO transcript_chunks
            (chunk_id, conversation_id, source_file, speaker_id,
             start_time, end_time, text, embedding)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s::vector)
        ON CONFLICT (chunk_id) DO UPDATE SET
            conversation_id = EXCLUDED.conversation_id,
            source_file = EXCLUDED.source_file,
            speaker_id = EXCLUDED.speaker_id,
            start_time = EXCLUDED.start_time,
            end_time = EXCLUDED.end_time,
            text = EXCLUDED.text,
            embedding = EXCLUDED.embedding
    """
    for chunk, embedding in zip(chunks, embeddings):
        vector_literal = "[" + ",".join(str(value) for value in embedding) + "]"
        connection.execute(
            sql,
            (
                chunk["chunk_id"], chunk["conversation_id"], chunk["source_file"],
                chunk["speaker_id"], chunk["start_time"], chunk["end_time"],
                chunk["text"], vector_literal,
            ),
        )
    connection.commit()
    logger.info("Inserted or updated %d chunks", len(chunks))
    return len(chunks)


def exact_cosine_search(connection, query_embedding: list[float], limit: int = 10):
    """Return nearest chunks using exact pgvector cosine distance.

    This is the quality baseline. It intentionally does not use an ANN index.
    The query embedding must be generated with the same local model as stored
    document embeddings.
    """
    vector_literal = "[" + ",".join(str(value) for value in query_embedding) + "]"
    return connection.execute(
        """
        SELECT chunk_id, conversation_id, source_file, speaker_id,
               start_time, end_time, text, embedding <=> %s::vector AS distance
        FROM transcript_chunks
        ORDER BY embedding <=> %s::vector ASC
        LIMIT %s
        """,
        (vector_literal, vector_literal, limit),
    ).fetchall()


def verify_storage(connection, expected_count: int) -> dict[str, Any]:
    """Verify row count, vector dimensions, speakers, and timestamp bounds."""
    row = connection.execute(
        """
        SELECT count(*) AS row_count,
               min(vector_dims(embedding)) AS min_dimension,
               max(vector_dims(embedding)) AS max_dimension,
               count(*) FILTER (WHERE speaker_id IS NULL) AS null_speakers,
               count(*) FILTER (WHERE end_time < start_time) AS invalid_times
        FROM transcript_chunks
        """
    ).fetchone()
    result = {
        "expected_count": expected_count,
        "row_count": row[0],
        "min_dimension": row[1],
        "max_dimension": row[2],
        "null_speakers": row[3],
        "invalid_times": row[4],
        "dimension_expected": DEFAULT_EMBEDDING_CONFIG.dimension,
    }
    logger.info("Storage verification: %s", result)
    return result
